language: rust
cache: cargo
sudo: required

rust:
  # - nightly
  # - beta
  - stable

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
  homebrew:
    packages:
      - sdl2
      - sdl2_mixer
      - sdl2_ttf

before_install:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CARGO_TARGET_DIR="$(pwd)/target"
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force --git https://github.com/xd009642/tarpaulin --tag 0.6.6 cargo-tarpaulin
    fi

env:
  global:
    - RUST_BACKTRACE=1

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      cargo build --verbose
      cargo tarpaulin --out Xml
      bash <(curl -s https://codecov.io/bash)
    else
      cargo build --verbose
      cargo test -- --nocapture
    fi
