name: Coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        use-tool-cache: true
    - name: Install dependencies
      run: sudo apt-get install -y --no-install-recommends libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev
    - name: Run coverage
      run: cargo tarpaulin -f -t 5 --out Xml -v
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cobertura.xml
