pub const LARGE_IMAGES: [[&[u8]; 6]; 6] = [
  [
    include_bytes!(concat!("./", "large", "/", "a1.bmp")),
    include_bytes!(concat!("./", "large", "/", "a2.bmp")),
    include_bytes!(concat!("./", "large", "/", "a3.bmp")),
    include_bytes!(concat!("./", "large", "/", "a4.bmp")),
    include_bytes!(concat!("./", "large", "/", "a5.bmp")),
    include_bytes!(concat!("./", "large", "/", "a6.bmp")),
  ],
  [
    include_bytes!(concat!("./", "large", "/", "b1.bmp")),
    include_bytes!(concat!("./", "large", "/", "b2.bmp")),
    include_bytes!(concat!("./", "large", "/", "b3.bmp")),
    include_bytes!(concat!("./", "large", "/", "b4.bmp")),
    include_bytes!(concat!("./", "large", "/", "b5.bmp")),
    include_bytes!(concat!("./", "large", "/", "b6.bmp")),
  ],
  [
    include_bytes!(concat!("./", "large", "/", "c1.bmp")),
    include_bytes!(concat!("./", "large", "/", "c2.bmp")),
    include_bytes!(concat!("./", "large", "/", "c3.bmp")),
    include_bytes!(concat!("./", "large", "/", "c4.bmp")),
    include_bytes!(concat!("./", "large", "/", "c5.bmp")),
    include_bytes!(concat!("./", "large", "/", "c6.bmp")),
  ],
  [
    include_bytes!(concat!("./", "large", "/", "d1.bmp")),
    include_bytes!(concat!("./", "large", "/", "d2.bmp")),
    include_bytes!(concat!("./", "large", "/", "d3.bmp")),
    include_bytes!(concat!("./", "large", "/", "d4.bmp")),
    include_bytes!(concat!("./", "large", "/", "d5.bmp")),
    include_bytes!(concat!("./", "large", "/", "d6.bmp")),
  ],
  [
    include_bytes!(concat!("./", "large", "/", "e1.bmp")),
    include_bytes!(concat!("./", "large", "/", "e2.bmp")),
    include_bytes!(concat!("./", "large", "/", "e3.bmp")),
    include_bytes!(concat!("./", "large", "/", "e4.bmp")),
    include_bytes!(concat!("./", "large", "/", "e5.bmp")),
    include_bytes!(concat!("./", "large", "/", "e6.bmp")),
  ],
  [
    include_bytes!(concat!("./", "large", "/", "f1.bmp")),
    include_bytes!(concat!("./", "large", "/", "f2.bmp")),
    include_bytes!(concat!("./", "large", "/", "f3.bmp")),
    include_bytes!(concat!("./", "large", "/", "f4.bmp")),
    include_bytes!(concat!("./", "large", "/", "f5.bmp")),
    include_bytes!(concat!("./", "large", "/", "f6.bmp")),
  ],
];
